version: '3'

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    ports:
      - "8080:80"
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    ports:
      - "8081:80"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - db-postgres
    environment:
      DSN: ${DSN}

  # this service name must be used as hostname in variable DSN
  # this is how the network is correctly routed to the database
  # NOTE: outside docker container, it would be localhost
  db-postgres:
    image: postgres:14.2-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/postgres:/var/lib/postgresql/data/
    deploy:
      mode: replicated
      replicas: 1

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "7000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "kfasunle@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"

    volumes:
      - ./db/pg_admin:/var/lib/pgadmin

volumes:
  postgres-db:
