version: '3'

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    ports:
      - ${BROKER_PORT}:80
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    ports:
      - ${AUTH_PORT}:80
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - db-postgres
    environment:
      DSN: ${DSN}

  logger-service:
    build:
      context: ./../logger-service
      dockerfile: ./../logger-service/logger-service.dockerfile
    # ports:
    #   - ${LOGGER_PORT}:80
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - db-mongo
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_NAME: ${MONGODB_NAME}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}

  # this service name must be used as hostname in variable DSN
  # this is how the network is correctly routed to the database
  # NOTE: outside docker container, it would be localhost
  db-postgres:
    image: postgres:14.2-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/postgres:/var/lib/postgresql/data/
    deploy:
      mode: replicated
      replicas: 1

  db-mongo:
    image: mongo:4.4-focal
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

    volumes:
      - ./db/mongo:/data/db
    deploy:
      mode: replicated
      replicas: 1
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - ${MAILHOG_PORT}:8025

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    volumes:
      - ./db/pg_admin:/var/lib/pgadmin

volumes:
  postgres-db:
  mongo-db:
    driver: local
